FROM debian

LABEL maintainer="Joshabel"

RUN apt update -y && apt install -y \
	net-tools \
	node \
	netcat \
	tcpdump \
	wget \
	curl \
	nmap \
	hydra \
	traceroute \
	git \
	hugo \
